packages:
  - 'apps/*'
  - 'packages/*'
  - 'core/*'

catalog:
  next: 15.4.5
  lucide-react: 0.536.0
  tailwindcss: 4.1.11
  eslint: 9.32.0
  prettier: 3.6.2
  typescript: 5.9.2
  react: 19.1.1
  react-dom: 19.1.1
  '@types/node': 22.15.21
  'zod': 3.25.64
  '@types/react': 19.1.9
  '@types/react-dom': 19.1.7
  '@turbo/gen': 2.5.5
  turbo: 2.5.5
  'react-hook-form': 7.62.0
  '@hookform/resolvers': 5.2.1
  'drizzle-kit': 0.31.4
