packages:
  - "apps/*"
  - "packages/*"

catalog:
  lucide-react: 0.475.0
  tailwindcss: 4.0.8
  eslint: 8.57.0
  prettier: 3.3.3
  typescript: 5.7.3
#  "@types/node": 20
#  "@types/eslint": 8
  "zod": 3.24.2
  "@types/react": 19.0.0
  "@types/react-dom": 19.0.0
