packages:
  - 'apps/*'
  - 'packages/*'
  - 'core/*'

catalog:
  next: 15.3.3
  lucide-react: 0.475.0
  tailwindcss: 4.1.8
  eslint: 8.57.0
  prettier: 3.5.3
  typescript: 5.7.3
  react: 19.1.0
  react-dom: 19.1.0
  '@types/node': 22.15.21
  'zod': 3.25.64
  '@types/react': 19.0.0
  '@types/react-dom': 19.0.0
  '@turbo/gen': 2.5.3
  turbo: 2.5.4
  'react-hook-form': 7.57.0
  '@hookform/resolvers': 5.1.1
  'drizzle-kit': 0.31.4
